### ISSUE TITLE
Issue creating VVJSONSchema using baseURI

### ISSUE THREAD

**Issue by lexicalunit** [vlas-voloshin/JSONSchemaValidation#1] opened 2015-01-21 17:15 UTC
I'm trying to create a `VVJSONSchema` object from a JSON schema file. The file has references to other JSON schema files in it. Here's my source code:

```objc
#import <Foundation/Foundation.h>
#import <VVJSONSchemaValidation/VVJSONSchema.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSError* error;
        NSURL *baseURI = [NSURL URLWithString:@"file:///Users/me/Desktop/"];
        NSData* schemaData = [NSData dataWithContentsOfFile:@"/Users/me/Desktop/schema.json"];
        error = nil;
        VVJSONSchema* schema = [VVJSONSchema schemaWithData:schemaData
                                                    baseURI:baseURI
                                           referenceStorage:nil
                                                      error:&error];
        if(error != nil) {
            NSLog(@"schema error: %@ %@", error, [error userInfo]);
            return 1;
        }
    }
    return 0;
}
```

Here are the relevant parts of the `schema.json` I am trying to load:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "context": {
            "allOf": [
                {
                    "$ref": "base/context.json#/context"
                },
[...]
```

On my desktop I have a folder named `base` which holds JSON schema that `schema.json` references. As you can see, the `base` directory has the file `context.json`:

```
$ cd ~/Desktop
$ ls base
context.json  [...]
```

When I build and run my code, I get the following error:

```
2015-01-21 11:06:21.923 JSONValidate[8702:356560] schema error:
    Error Domain=com.argentumko.JSONSchemaValidationError
    Code=105 "The operation couldn’t be completed. (com.argentumko.JSONSchemaValidationError error 105.)"
    UserInfo=0x10011d310 {object=file:///Users/me/Desktop/base/context.json#/context} {
        object = "file:///Users/me/Desktop/base/context.json#/context";
    }
Program ended with exit code: 1
```

**Comment by lexicalunit** [comment] 2015-01-21 19:39
Going of some of the code I found in the tests and library itself, I tried to workaround this issue using a `VVJSONSchemaFactory` object, but doing so has caused a different issue: Validation always succeeds, even when it shouldn't.

Modified code:

```objc
#import <Foundation/Foundation.h>
#import <VVJSONSchemaValidation/VVJSONSchema.h>
#import <VVJSONSchemaValidation/VVJSONSchemaFactory.h>

#define USE_FACTORY 0

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSError* error;

        // create schema factory with base url
        NSURL *baseURI = [NSURL URLWithString:@"file:///Users/me/Desktop/JSON/"];
        NSDictionary *keywordsMapping = [NSDictionary dictionary];
        VVJSONSchemaFactory *factory = [VVJSONSchemaFactory factoryWithScopeURI:baseURI keywordsMapping:keywordsMapping];
        if(!factory) {
            NSLog(@"factory fail!");
            return 1;
        }

        // load schema
        NSData *schemaData = [NSData dataWithContentsOfFile:@"/Users/me/Desktop/JSON/app/discover/Scroll.json"];
        error = nil;
        NSDictionary *schemaEvent = [NSJSONSerialization JSONObjectWithData:schemaData options:0 error:&error];
        if(error) {
            NSLog(@"error: %@ %@", error, [error userInfo]);
            return 1;
        }

        error = nil;
        VVJSONSchema *schema = [factory schemaWithDictionary:schemaEvent error:&error];
        if(error != nil) {
            NSLog(@"error: %@ %@", error, [error userInfo]);
            return 1;
        }

        // load test data and validate against loaded schema
        NSData* testData = [NSData dataWithContentsOfFile:@"/Users/me/Desktop/JSON/bad.json"]; // BAD TEST DATA!
        error = nil;
        NSDictionary *testEvent = [NSJSONSerialization JSONObjectWithData:testData options:0 error:&error];
        if(error != nil) {
            NSLog(@"error: %@ %@", error, [error userInfo]);
            return 1;
        }
        
        NSLog(@"schema: %@", schema);
        NSLog(@"test: %@", testEvent);
        
        error = nil;
        BOOL success = [schema validateObjectWithData:testData error:&error];
        if(!success || error) {
            NSLog(@"error: %@ %@", error, [error userInfo]);
            return 1;
        } else {
            NSLog(@"Validation success!");
        }
    }
    return 0;
}
```

Generates the following output:

```
2015-01-21 13:34:10.934 JSONValidate[15766:620391] schema:
    <VVJSONSchema: 0x100118390>{
        file:///Users/me/Desktop/JSON/;
        'app.discover.Scroll': '"Scroll" event in category "discover" for "app" platform. Use Case: scroll';
        0 validators;
        1 subschemas 
    }
2015-01-21 13:34:10.936 JSONValidate[15766:620391] test: {
    context =     {
        appForeground = "not a bool";
        beaconSessionId = 3;
        carrier = 2;
        deviceId = 1;
        environment = production;
        favoriteFlag = true;
        instoreFlag = true;
    };
    event =     {
        eventInstanceId = 1;
        eventTimestamp = 4;
        eventVersion = 5;
    };
}
2015-01-21 13:34:10.936 JSONValidate[15766:620391] Validation success!
Program ended with exit code: 0
```

The validation should absolutely not succeed in this case. Also, it doesn't matter what I use as `factoryWithScopeURI`, it seems to have no effect what-so-ever.

**Comment by lexicalunit** [comment] 2015-01-21 20:01
I thought this might be an issue with `file://` so to test I uploaded the schemas to my webserver and used that, so that the `baseURI` would use `http://`, but I ran into the exact same errors.

**Comment by vlas-voloshin** [comment] 2015-01-21 23:10
Hey there! Thanks for your interest in the library.
Code 105 stands for `VVJSONSchemaErrorCodeUnresolvableSchemaReference` (error messages probably should be a bit more informative, yeah, I'll work on that soon). Unfortunately, as it is stated in "known issues and caveats", loading schema references from external locations is not supported right now. Basically, the library decidedly has no way to download any other schemas, neither from local URIs or network URIs. Though I might reconsider this in the future (and find a good method to opt-in to downloading remote schemas), currently you'll need to use `VVJSONSchemaStorage` class to "preload" referenced schemas in advance manually, as described here: https://github.com/vlas-voloshin/JSONSchemaValidation#schema-storage-and-external-references
Please also refer to documentation in headers, when necessary: I tried to make them more or less informative.
Also note that `VVJSONSchemaFactory` class is not fit for stand-alone use right now – it's used internally and provided only for those who would like to build custom validation keywords. Basically, by providing an empty keywords dictionary, you made sure the factory does know how to handle any schema keywords :smile:

**Comment by lexicalunit** [comment] 2015-01-21 23:48
When you say you don't support external locations do you mean you don't support `"$ref"` at all? These aren't really "external" schemas, they're all just files downloaded to my laptop, or files stuffed into my xcode project are resources/bundle.

I have done some experimentation with `VVJSONSchemaStorage` as well but had issues with it:

```objc
NSError *error;
VVMutableJSONSchemaStorage *storage = [VVMutableJSONSchemaStorage storage];
NSURL *baseRemoteSchemasURI = [[NSBundle mainBundle] bundleURL];
NSLog(@"base: %@", baseRemoteSchemasURI);

NSURL *url;
NSData *data;
VVJSONSchema *s;
BOOL added;

NSLog(@"loading event.json...");
url = [[NSBundle mainBundle] URLForResource:@"event" withExtension:@"json"];
data = [NSData dataWithContentsOfURL:url];
s = [VVJSONSchema schemaWithData:data baseURI:baseRemoteSchemasURI referenceStorage:storage error:&error];
if(error) { NSLog(@"error: %@ %@", error, [error userInfo]); return; }
storage = [VVMutableJSONSchemaStorage storageWithSchema:s];

NSLog(@"loading inventory.json...");
url = [[NSBundle mainBundle] URLForResource:@"inventory" withExtension:@"json"];
data = [NSData dataWithContentsOfURL:url];
s = [VVJSONSchema schemaWithData:data baseURI:baseRemoteSchemasURI referenceStorage:storage error:&error];
if(error) { NSLog(@"error: %@ %@", error, [error userInfo]); return; }
storage = [VVMutableJSONSchemaStorage storageWithSchema:s];
```

I get an error trying to load the 2nd schema, `inventory`. My output:

```
2015-01-21 17:18:01.876 TestApplication[32669:1632100] base: file:///Users/me/Library/Developer/CoreSimulator/Devices/307C22CC-E288-4531-ADD2-0E6629769A28/data/Containers/Bundle/Application/953E5730-2DAF-401C-8181-CC00069C188C/TestApplication.app/
2015-01-21 17:18:01.876 TestApplication[32669:1632100] loading event.json...
2015-01-21 17:18:01.883 TestApplication[32669:1632100] loading inventory.json...
2015-01-21 17:18:01.892 TestApplication[32669:1632100] error: Error Domain=com.argentumko.JSONSchemaValidationError Code=103 "The operation couldn’t be completed. (com.argentumko.JSONSchemaValidationError error 103.)" UserInfo=0x7ff32369a970 {object=<CFBasicHash 0x7ff32369a800 [0x10b2989a0]>{type = immutable dict, count = 2,
entries =>
	0 : <CFString 0x7ff323694660 [0x10b2989a0]>{contents = "$schema"} = <CFString 0x7ff323615bc0 [0x10b2989a0]>{contents = "http://json-schema.org/draft-04/schema#"}
	2 : <CFString 0x7ff32368d090 [0x10b2989a0]>{contents = "inventory"} = <CFBasicHash 0x7ff32369a740 [0x10b2989a0]>{type = immutable dict, count = 6,
entries =>
	0 : <CFString 0x7ff323697520 [0x10b2989a0]>{contents = "derived"} = <CFArray 0x7ff3236967a0 [0x10b2989a0]>{type = immutable, count = 1, values = (
	0 : <CFString 0x7ff3236972f0 [0x10b2989a0]>{contents = "viewInstanceId"}
)}
	1 : <CFString 0x7ff32368ed90 [0x10b2989a0]>{contents = "properties"} = <CFBasicHash 0x7ff32369a390 [0x10b2989a0]>{type = immutable dict, count = 31,
entries =>
	0 : <CFString 0x7ff323695ee0 [0x10b2989a0]>{contents = "curatedFlag"} = <CFBasicHash 0x7ff3236995e0 [0x10b2989a0]>{type = immutable dict, count = 4,
entries =>
	2 : <CFString 0x7ff32368d1d0 [0x10b2989a0]>{contents = "shortened"} = <CFString 0x7ff3236995c0 [0x10b2989a0]>{contents = "cu"}
	4 : <CFString 0x7ff323696010 [0x10b2989a0]>{contents = "description"} = <CFString 0x7ff323699560 [0x10b2989a0]>{contents = "To group activity by content being published organically or through curation"}
	5 : <CFString 0x7ff32368c960 [0x10b2989a0]>{contents = "example"} = <CFBoolean 0x10b299410 [0x10b2989a0]>{value = true}
	6 : <CFString 0x7ff32368db10 [0x10b2989a0]>{contents = "type"} = <CFString 0x7ff32368e850 [0x10b2989a0]>{contents = "boolean"}
}

[...]
```

**Comment by vlas-voloshin** [comment] 2015-01-22 00:03
`$ref` keywords are supported, but the limitation is that the schema referenced by it must either exist in the very schema you're parsing (as a subschema, so you'd be referencing it by a JSON pointer), _or_ it must be already contained in the `VVJSONSchemaStorage` specified when creating a schema, with correct base URI specified.
Code 103 stands for `VVJSONSchemaErrorCodeDuplicateResolutionScope`. Here's what happened:

* First, you're creating a schema out of `event.json`, specifying the main bundle URL as its base reference URI, and an empty storage. That's fine, but I guess `event.json` doesn't redefine its scope using `id` keyword, so the schema scope URI would be the main bundle URL.
* Then you're creating another schema out of `inventory.json`, again, specifying the main bundle URL as its base reference URI, but now also a storage with existing schema from `event.json`. I can guess that `inventory.json` doesn't define its scope URI either, so it is determined to also be the main bundle URL. Since a schema with such scope URI already appears in the storage you've supplied, there's a URI conflict.

I'd suggest specifying `url` variable you have there as the base URI – it's more correct this way and won't cause the name/URI conflict.

**Comment by lexicalunit** [comment] 2015-01-22 00:16
Ah, ok, I reworked the previously posted code a bit... Different error now:

```objc

void addSchema(NSString *name, VVMutableJSONSchemaStorage *storage)
{
    NSLog(@"loading %@.json...", name);
    NSURL *url = [[NSBundle mainBundle] URLForResource:name withExtension:@"json"];
    NSData *data = [NSData dataWithContentsOfURL:url];
    NSError *error = nil;
    VVJSONSchema *s = [VVJSONSchema schemaWithData:data baseURI:url referenceStorage:storage error:&error];
    if(error) { NSLog(@"error: %@ %@", error, [error userInfo]); return; }
    BOOL added = [storage addSchema:s];
    if(!added) { NSLog(@"not added"); return; }
}

[...]

    VVMutableJSONSchemaStorage *storage = [VVMutableJSONSchemaStorage storage];

    addSchema(@"event", storage);
    addSchema(@"inventory", storage);
    addSchema(@"marketing", storage);
    addSchema(@"performance", storage);
    addSchema(@"test", storage);
    addSchema(@"vendor", storage);
    addSchema(@"context", storage);

[...]
```

I get an error trying to add the final schema, `context`, which has `$ref`s to the other schemas, which should already be loaded into the storage object. My output:

```
2015-01-21 18:06:25.993 MyApp[36116:1721652] loading event.json...
2015-01-21 18:06:25.999 MyApp[36116:1721652] loading inventory.json...
2015-01-21 18:06:26.001 MyApp[36116:1721652] loading marketing.json...
2015-01-21 18:06:26.003 MyApp[36116:1721652] loading performance.json...
2015-01-21 18:06:26.005 MyApp[36116:1721652] loading test.json...
2015-01-21 18:06:26.005 MyApp[36116:1721652] loading vendor.json...
2015-01-21 18:06:26.006 MyApp[36116:1721652] loading context.json...
2015-01-21 18:06:26.016 MyApp[36116:1721652] error: Error Domain=com.argentumko.JSONSchemaValidationError Code=105 "The operation couldn’t be completed. (com.argentumko.JSONSchemaValidationError error 105.)" UserInfo=0x7f852147c940 {object=file:///Users/me/Library/Developer/CoreSimulator/Devices/307C22CC-E288-4531-ADD2-0E6629769A28/data/Containers/Bundle/Application/DEBBE3F7-AEE1-49C2-8EF6-4E2C09B73526/MyApp.app/base/marketing.json#/marketing} {
    object = "file:///Users/me/Library/Developer/CoreSimulator/Devices/307C22CC-E288-4531-ADD2-0E6629769A28/data/Containers/Bundle/Application/DEBBE3F7-AEE1-49C2-8EF6-4E2C09B73526/MyApp.app/base/marketing.json#/marketing";
}
```

BTW thank you for the help! :)

**Comment by lexicalunit** [comment] 2015-01-22 00:20
Oh, and the code in `context.json` that seems to be causing the issue is:

```json
            "test": {
                "$ref": "test.json#/test",
                "shortened": "t"
            }
```

And the `url` for `test.json` is:

```
file:///Users/me/Library/Developer/CoreSimulator/Devices/307C22CC-E288-4531-ADD2-0E6629769A28/data/Containers/Bundle/Application/9CDE7CFE-76EA-4448-8F28-091A0D6E3E01/buttfart.app/test.json
```

**Comment by vlas-voloshin** [comment] 2015-01-22 00:27
Alright, the failing reference URI is, as you can see, `<simulator_container>/MyApp.app/base/marketing.json#/marketing`, so the `$ref` URI is probably `marketing.json#/marketing`. Make sure that `marketing.json` schema actually has a `marketing` subschema in its root.
Please notice the error messages (the code and object) – they should give an idea what's actually wrong.
Also make sure that you use the latest (1.2.0) version of the library – the previous one didn't support storing "standalone" subschemas outside of keywords like `definitions` and such, like `marketing` in this case.

**Comment by lexicalunit** [comment] 2015-01-22 00:34
Hrm, so I am using the correct `$ref` in `context.json` by using `markering.json#/marketing`?

The `marketing.json` file looks like this:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "marketing": {
        "derived": [
            "viewInstanceId"
        ],
        "properties": {
            "adGroup": {
                "description": "To group activity by paid term Ad Group",
                "example": "",
                "shortened": "ag",
                "type": "string"
            },

[...]

        },
        "required": [
            "marketingInstanceId"
        ],
        "shortened": "m",
        "type": "object"
    }
}
```

**Comment by lexicalunit** [comment] 2015-01-22 00:40
And I am using a podfile with

```
pod 'VVJSONSchemaValidation', '1.2.0'
```

To add the library to my project workspace. So hopefully I am using version 1.2.0 :)

**Comment by lexicalunit** [comment] 2015-01-22 00:53
I'm not 100% here but, is it the case that my `marketing.json` doesn't have a "subschema"? I'm not familiar with JSON Schema 4.0, these schema files are simply handed down to my from up-on-high and I want to validate generated JSON against them as easy as possible.

**Comment by vlas-voloshin** [comment] 2015-01-22 00:59
`marketing.json` looks correct. That `marketing` property in its root should have been translated as a subschema with `marketing.json#/marketing` scope URI, so referencing it like this from `context.json` should have worked...
I will have to reproduce your scenario myself tonight to debug it appropriately and see what goes wrong with parsing. If you could drop me an email with your schema files so that I have a clear test case, it would be great, but hopefully it wouldn't be too difficult for me to imitate them.

**Comment by vlas-voloshin** [comment] 2015-01-22 12:10
I've tried reproducing your situation using the loading code you posted earlier and the following two schemas:

```
context.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "context": {
		"properties" : {
			"marketing": {
				"$ref": "marketing.json#/marketing",
		                "shortened": "m"
		        }
		}
    }
}

marketing.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "marketing": {
        "derived": [
            "viewInstanceId"
        ],
        "properties": {
            "adGroup": {
                "description": "To group activity by paid term Ad Group",
                "example": "",
                "shortened": "ag",
                "type": "string"
            }
        },
        "required": [
            "marketingInstanceId"
        ],
        "shortened": "m",
        "type": "object"
    }
}
```

It worked fine though. Please note that inside an iOS app bundle, resource files like JSONs are laid out "plainly" by default: all in the same directory on disk. That's unless you use "folders" instead of "groups" when adding those files into your Xcode project (folders are blue, groups are yellow). This means that some of the "real" URIs of the loaded schemas (returned from `[[NSBundle mainBundle] URLForResource:name withExtension:@"json"];`) could be different from the relative URIs used in schema references. That's another reason why JSONSchema library actually allows its users to specify the base scope URI.
Notice, for example, the physical URI of your `marketing.json` file:
`file:///Users/me/Library/Developer/CoreSimulator/Devices/307C22CC-E288-4531-ADD2-0E6629769A28/data/Containers/Bundle/Application/9CDE7CFE-76EA-4448-8F28-091A0D6E3E01/MyApp.app/marketing.json` – it's in the root directory of your app bundle. Next time you'll have the reference error, you might want to take a look inside your compiled app bundle (it's in Derived Data directory of your project) and see where's the file being referenced. Then try printing the description of the expected schema object, it would output something like this:

```
<VVJSONSchema: 0x7f891ca61ac0>{ file:///Users/vlas/Library/Developer/CoreSimulator/Devices/E31C9253-4B0A-4F73-94CE-E56FC1668910/data/Containers/Bundle/Application/62FC0135-3234-4442-B357-5624D774FB52/JSONTest.app/context.json#; '(null)': '(null)'; 0 validators; 1 subschemas }
```

Notice the URI at the beginning – it's schema's base scope URI. You could also try to output the URI mapping of the schema storage by typing this in the debugger console: `po storage->_mapping – it will output a dictionary of URIs and schemas in that storage. See if the schema you're expecting is there with a correct URI.

**Comment by lexicalunit** [comment] 2015-01-22 16:12
It works! You rock, thank you so much :)

I thought xcode was just storing the files in a flat hierarchy but maintaining metadata about their "paths" (or something like that), and didn't realize that the behavior I really wanted was `folders` rather than `groups`.

To close the loop, here's my final code:

```objc
void addSchema(NSString *name, VVMutableJSONSchemaStorage *storage)
{
    NSLog(@"loading %@.json...", name);
    NSURL *url = [[NSBundle mainBundle] URLForResource:name withExtension:@"json"];
    if(!url) { NSLog(@"url not found for resource name %@", name); return; }
    NSData *data = [NSData dataWithContentsOfURL:url];
    if(!data) { NSLog(@"data not loaded from url %@", url); return; }
    NSError *error = nil;
    VVJSONSchema *s = [VVJSONSchema schemaWithData:data baseURI:url referenceStorage:storage error:&error];
    if(error) { NSLog(@"error: %@ %@", error, [error userInfo]); return; }
    BOOL added = [storage addSchema:s];
    if(!added) { NSLog(@"not added"); return; }
}

[...]

    NSURL *bundleURL = [[NSBundle mainBundle] bundleURL];
    NSLog(@"bundleURL: %@", bundleURL);

    VVMutableJSONSchemaStorage *storage = [VVMutableJSONSchemaStorage storage];
    addSchema(@"base/event", storage);
    addSchema(@"base/inventory", storage);
    addSchema(@"base/marketing", storage);
    addSchema(@"base/performance", storage);
    addSchema(@"base/test", storage);
    addSchema(@"base/vendor", storage);
    addSchema(@"base/context", storage);

    // load and serialize as JSON the Scroll event
    NSURL *schemaURL = [[NSBundle mainBundle] URLForResource:@"app/discover/Scroll" withExtension:@"json"];
    error = nil;
    NSData *schemaData = [NSData dataWithContentsOfURL:schemaURL];
    if(!schemaData) {
        NSLog(@"error:%d: %@ %@", __LINE__, error, [error userInfo]);
        return;
    }

    error = nil;
    NSDictionary *schemaDict = [NSJSONSerialization JSONObjectWithData:schemaData options:0 error:&error];
    if(error) {
        NSLog(@"error:%d: %@ %@", __LINE__, error, [error userInfo]);
        return;
    }

    VVJSONSchema *schema = [VVJSONSchema schemaWithDictionary:schemaDict
                                                      baseURI:bundleURL
                                             referenceStorage:storage
                                                        error:&error];
    if(!schema || error) {
        NSLog(@"error:%d: %@ %@", __LINE__, error, [error userInfo]);
        return;
    }

[...]
```

The only remaining issue is that I have to be sure to load the schemas into the storage in the correct order, so that I never try to load a schema which has `$ref`s to schemas that I haven't yet loaded. Do you have a suggestion or workaround to resolve that issue?

**Comment by vlas-voloshin** [comment] 2015-01-23 00:21
Awesome! I'm glad it works.
Yeah, the scenario of "intertwined" external subschemas is something I would need to improve on in the library: maybe by actually allowing to load external schemas, or by allowing "lazily resolved" references. For now, I can only suggest an alternative of keeping all "base" schemas in the same file like this:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
	"definitions": {
	    "marketing": {
	                "id": "marketing.json#/marketing"
			[...]
		},
		"context": {
			"id": "context.json#/context"
                        "properties" : {
				"marketing": {
					"$ref": "marketing.json#/marketing",
			                "shortened": "m"
			        }
			}
			[...]
		},
		[...]
	}
}
```

`id` keyword can be there used to redefine resolution scope, so that a subschema would actually have a different URI than the one derived from specified base URI and its JSON path. But of course that's only a viable solution if you don't have to update all your schemas on a regular basis.

**Comment by vlas-voloshin** [comment] 2015-01-27 06:32
As the problem seems to be solved, I'm closing this. Feel free to reopen if there are any other issues.

**Closed by vlas-voloshin** 2015-01-27 06:32 UTC
